---
name: Check Python code
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ubuntu-version:
        type: string
        default: '22.04'

jobs:

  check-code:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - name: Lint (with ruff)
        run: poetry run ruff .

      - name: Check formatting (with black)
        run: poetry run black .

      - name: Type check (with pyright)
        run: poetry run pyright .
