---
name: Upload coverage to SonarCloud

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ubuntu-version:
        type: string
        default: '22.04'
      python-version:
        type: string
        default: '3.9'
      poetry-version:
        type: string
        default: '1.4.0'
    secrets:
      SONAR_TOKEN:
        required: false
        description: >
          see https://sonarcloud.io/account/security/

jobs:
  upload:
    runs
    steps:
      - name: Upload coverage results
        # https://docs.sonarcloud.io/enriching/test-coverage/python-test-coverage/
        if: ${{ env.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
