---
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ubuntu-version:
        type: string
        default: '22.04'
      python-version:
        type: string
        default: '3.9'
      poetry-version:
        type: string
        default: '1.4.0'
    secrets:
      SONAR_TOKEN:
        required: false
        description: >
          see https://sonarcloud.io/account/security/

jobs:

  install-dependencies:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install package manager (Poetry)
        run: pipx install poetry==${{inputs.poetry-version}}

      - uses: actions/setup-python@v4
        with:
          python-version: '${{inputs.python-version}}'
          cache: 'poetry'

      - name: Install Python packages
        run: poetry install

  check-code:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - name: Lint (with ruff)
        run: poetry run ruff .

      - name: Check formatting (with black)
        run: poetry run black .

      - name: Type check (with pyright)
        run: poetry run pyright .

  test-and-track-coverage:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - name: Test (with pytest) and track coverage
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --cov-report=xml

  upload-coverage-report-to-sonarcloud:
    runs
    steps:
      - name: Upload coverage results
        # https://docs.sonarcloud.io/enriching/test-coverage/python-test-coverage/
        if: ${{ env.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

  test:
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install package manager (Poetry)
        run: pipx install poetry==${{inputs.poetry-version}}

      - uses: actions/setup-python@v4
        with:
          python-version: '${{inputs.python-version}}'
          cache: 'poetry'

      - name: Install Python packages
        run: poetry install

      - name: Lint
        run: poetry run ruff .

      - name: Check formatting
        run: poetry run black .

      - name: Type check
        run: poetry run pyright .

      - name: Test
        env:
          SLACK_BOT_TOKEN: xoxb-a-big-nothing-burger
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --cov-report=xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: coverage.xml
        if: ${{ always() }}

      - name: Upload coverage results
        # https://docs.sonarcloud.io/enriching/test-coverage/python-test-coverage/
        if: ${{ env.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
