---
name: Test (with Pytest)

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ubuntu-version:
        type: string
        default: '22.04'

jobs:

  test-and-track-coverage:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - name: Run pytest
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --cov-report=xml
