---
name: Install dependencies (with Poetry)

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ubuntu-version:
        type: string
        default: '22.04'
      python-version:
        type: string
        default: '3.9'
      poetry-version:
        type: string
        default: '1.4.0'
    secrets:
      SONAR_TOKEN:
        required: false
        description: >
          see https://sonarcloud.io/account/security/

jobs:

  install-dependencies:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install package manager (Poetry)
        run: pipx install poetry==${{inputs.poetry-version}}

      - uses: actions/setup-python@v4
        with:
          python-version: '${{inputs.python-version}}'
          cache: 'poetry'

      - name: Install Python packages
        run: poetry install
