---
on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  test-python-poetry:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install package manager (Poetry)
        run: pipx install poetry==1.4.0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
          cache: 'poetry'
      - name: Install Python packages
        run: poetry install
      - name: Lint
        run: poetry run ruff .
      - name: Check formatting
        run: poetry run black .
      - name: Type check
        run: poetry run pyright .
      - name: Test
        run: |
          poetry run pytest \
            --junitxml=junit/test-results.xml \
            --cov=. --cov-report=xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/
        if: ${{ always() }}
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: coverage.xml
        if: ${{ always() }}
