---
name: Capture Pytest results

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ubuntu-version:
        type: string
        default: '22.04'

jobs:

  store-test-and-coverage-report:
    runs-on: ubuntu-${{inputs.ubuntu-version}}

    steps:
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: coverage.xml
        if: ${{ always() }}
