---
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      report-to-sonarcloud:
        required: true
        type: boolean
        default: false
      report-to-codacy:
        required: true
        type: boolean
        default: false

      test-report-artifact:
        required: true
        description: pytest-results when using python-with-poetry
        type: string

      coverage-report-artifact:
        required: true
        type: string
      coverage-report-path:
        required: false
        default: coverage.xml
        type: string

    secrets:
      SONAR_TOKEN:
        required: ${{ inputs.report-to-sonarcloud }}
        description: >
          see https://sonarcloud.io/account/security/
      SONAR_PROJECT_KEY:
        required: ${{ inputs.report-to-sonarcloud }}
      # TODO: Consider removing as this is always the same
      SONAR_ORGANIZATION_KEY:
        required: ${{ inputs.report-to-sonarcloud }}
      CODACY_PROJECT_TOKEN:
        required: ${{ inputs.report-to-codacy }}

jobs:
  # TODO: Eval merging the jobs such to retrieve code artifacts once and branch
  # out publishing if the code and artifact retrieval take considerable time.
  report_to_sonarcloud:
    name: Report to SonarCloud
    runs-on: ubuntu-22.04
    if: ${{ inputs.report-to-sonarcloud }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: properties
        name: Setup sonar-project.properties
        env:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
        run: |
          echo "sonar.projectKey=$SONAR_PROJECT_KEY" \
            >> sonar-project.properties
          echo "sonar.organization=$SONAR_ORGANIZATION_KEY" \
            >> sonar-project.properties
          echo "sonar.python.coverage.reportPaths=coverage.xml" \
            >> sonar-project.properties
          echo "sonar.python.version=3" \
            >> sonar-project.properties
          echo "sonar.sources=." \
            >> sonar-project.properties
          cat sonar-project.properties
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.test-report-artifact }}
          path: junit/
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.coverage-report-artifact }}
      - name: Modify paths in coverage report
        run: |
          sed -i \
          "s#<source>[^<]*</source>#<source>/github/workspace</source>#g" ${{ inputs.coverage-report-path }} \
          && head coverage.xml
      - run: pwd && tree
      - name: Publish
        # https://docs.sonarcloud.io/enriching/test-coverage/python-test-coverage/
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  report_to_codacy:
    name: Report to Codacy
    runs-on: ubuntu-22.04
    if: ${{ inputs.report-to-codacy }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.test-report-artifact }}
          path: junit/
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.coverage-report-artifact }}
      - run: pwd && tree
      - name: Publish
        # https://docs.sonarcloud.io/enriching/test-coverage/python-test-coverage/
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
